from dataclasses import dataclass

@dataclass
class TrainConfig:
    # --- Paths ---
    # Directory where setup.py downloaded the files
    model_dir: str = "./pretrained_models"
    
    # Path to your metadata CSV (Format: ID|RawText|NormText)
    csv_path: str = "./MyTTSDataset/metadata.csv"
    
    # Directory containing WAV files
    wav_dir: str = "./MyTTSDataset/wavs"
    #wav_dir: str = "./FileBasedDataset"
    
    preprocessed_dir = "./MyTTSDataset/preprocess"
    #preprocessed_dir = "./FileBasedDataset/preprocess"
    
    # Output directory for the finetuned model
    output_dir: str = "./chatterbox_output"

    ljspeech = True # Set True if the dataset format is ljspeech, and False if it's file-based.
    preprocess = True # If you've already done preprocessing once, set it to false.
    
    is_turbo: bool = True # Set True if you're training Turbo, False if you're training Normal.

    # --- Vocabulary ---
    # The size of the NEW vocabulary (from tokenizer.json)
    # Ensure this matches the JSON file generated by your tokenizer script.
    # For Turbo mode: Use the exact number provided by setup.py (e.g., 52260)
    new_vocab_size: int = 52260 if is_turbo else 2454 

    # --- Hyperparameters ---
    batch_size: int = 16        # Optimized for A100
    grad_accum: int = 2        # Effective Batch Size = 16 * 2 = 32
    learning_rate: float = 5e-5 # T3 is sensitive, keep low
    num_epochs: int = 30
    
    # --- Acceleration Settings ---
    use_bf16: bool = True  # Use BF16 precision (A100 optimized)
    use_torch_compile: bool = True  # Enable torch.compile for 20-50% speedup
    use_flash_attention: bool = True  # Use Flash Attention 2 if available
    
    # --- Checkpointing ---
    save_steps_fixed: int = 5000  # Save checkpoint every N steps
    save_at_epoch_end: bool = True  # Also save checkpoint at the end of each epoch
    save_total_limit: int = 10  # Keep last N checkpoints (inference files not affected)
    
    # --- Resume Training ---
    resume_from_checkpoint: bool = False  # Set True to resume from latest checkpoint

    # --- Constraints ---
    start_text_token = 255
    stop_text_token = 0
    max_text_len: int = 256
    max_speech_len: int = 850   # Truncates very long audio
    prompt_duration: float = 3.0 # Duration for the reference prompt (seconds)
