from dataclasses import dataclass

@dataclass
class TrainConfig:
    # --- Paths ---
    # Directory where setup.py downloaded files
    model_dir: str = "./pretrained_models"

    # Parquet dataset support
    use_parquet: bool = False  # If True, use parquet dataset instead of preprocessed files
    parquet_path: str = None   # Path to parquet directory (required if use_parquet=True)

    # Path to your metadata CSV (Format: ID|RawText|NormText)
    csv_path: str = "./MyTTSDataset/metadata.csv"

    # Directory containing WAV files
    wav_dir: str = "./MyTTSDataset/wavs"
    #wav_dir: str = "./FileBasedDataset"

    preprocessed_dir = "./MyTTSDataset/preprocess"
    #preprocessed_dir = "./FileBasedDataset/preprocess"

    # Output directory for finetuned model
    output_dir: str = "./chatterbox_output"

    ljspeech = True # Set True if dataset format is ljspeech, and False if it's file-based.
    preprocess = True # If you've already done preprocessing once, set it to false.

    max_samples: int = None     # Limit samples for testing (None = use all)

    is_turbo: bool = True # Set True if you're training Turbo, False if you're training Normal.

    # --- Vocabulary ---
    # The size of the NEW vocabulary (from tokenizer.json)
    # Ensure this matches JSON file generated by your tokenizer script.
    # For Turbo mode: Use exact number provided by setup.py (e.g., 52260)
    new_vocab_size: int = 52260 if True else 2454

    # --- Hyperparameters ---
    batch_size: int = 4         # Adjust based on VRAM (2, 4, 8)
    grad_accum: int = 2        # Effective Batch Size = Batch * Accum
    learning_rate: float = 5e-5 # T3 is sensitive, keep low
    num_epochs: int = 250

    # --- Constraints ---
    start_text_token = 255
    stop_text_token = 0
    max_text_len: int = 256
    max_speech_len: int = 850   # Truncates very long audio
    prompt_duration: float = 3.0 # Duration for reference prompt (seconds)
